spring.application.name=microservicio-demo01

server.port=8081

spring.datasource.url=jdbc:postgresql://postgres-db:5432/facturaciondb
spring.datasource.username=postgres

spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Activar OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Forzar uso de YAML estático
springdoc.swagger-ui.url=/openapi.yaml

# Evitar conflictos con anotaciones Java
springdoc.api-docs.groups.enabled=false
springdoc.cache.disabled=true
