spring.application.name=microservicio-demo01

server.port=8081

# BASE DE DATOS
# -- LOCAL (IntelliJ + Docker Compose) -- ACTIVO
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/microservicio_facturacion}
#
# -- KUBERNETES -- comentado
spring.datasource.url=jdbc:postgresql://postgres-db:5432/facturaciondb
#
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SWAGGER ---
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.groups.enabled=false
springdoc.cache.disabled=true

# --- MICROSERVICIOS EXTERNOS ---
microservicio.clientes.url=${MICROSERVICIO_CLIENTES_URL:http://4.206.202.17:8081}

# PRODUCTOS - IP actualizada por el equipo de productos
# Endpoints disponibles en esta base:
#   GET  /api/productos
#   PUT  /api/productos/reducir-stock
#   GET  /api/productos/{id}/portada/render
microservicio.productos.url=${MICROSERVICIO_PRODUCTOS_URL:http://40.82.168.11:8090}

# REDUCIR STOCK - misma IP base que productos
microservicio.productos.reducir-stock.url=${MICROSERVICIO_PRODUCTOS_REDUCIR_STOCK_URL:http://40.82.168.11:8090}